console.log("content Scripts")

var IPHdata = {
  "DE_ARI_ABDrop_Ship_Abuse_Referrals": 30.0,
  "ES_ARI_ABDrop_Ship_Abuse_Referrals": 30.0,
  "FR_ARI_ABDrop_Ship_Abuse_Referrals": 21.0,
  "GB_ARI_ABDrop_Ship_Abuse_Referrals": 30.0,
  "IT_ARI_ABDrop_Ship_Abuse_Referrals": 30.0,
  "JP_ARI_ABDrop_Ship_Abuse_Referrals": 30.0,
  "US_ARI_ABDrop_Ship_Abuse_Referrals": 30.0,
  "JP_ARI_Abuse_BCA_Queue": 27.2,
  "AE_ARI_Abuse_QtyLimit_Queue": 10.0,
  "AU_ARI_Abuse_QtyLimit_Queue": 25.0,
  "BE_ARI_Abuse_QtyLimit_Queue": 10.0,
  "BR_ARI_Abuse_QtyLimit_Queue": 10.0,
  "CA_ARI_Abuse_QtyLimit_Queue": 10.0,
  "DE_ARI_Abuse_QtyLimit_Queue": 10.0,
  "EG_ARI_Abuse_QtyLimit_Queue": 10.0,
  "ES_ARI_Abuse_QtyLimit_Queue": 10.0,
  "FR_ARI_Abuse_QtyLimit_Queue": 10.0,
  "IT_ARI_Abuse_QtyLimit_Queue": 10.0,
  "JP_ARI_Abuse_QtyLimit_Queue": 22.9,
  "MX_ARI_Abuse_QtyLimit_Queue": 10.0,
  "NL_ARI_Abuse_QtyLimit_Queue": 10.0,
  "PL_ARI_Abuse_QtyLimit_Queue": 10.0,
  "SA_ARI_Abuse_QtyLimit_Queue": 10.0,
  "SE_ARI_Abuse_QtyLimit_Queue": 10.0,
  "SG_ARI_Abuse_QtyLimit_Queue": 10.0,
  "TR_ARI_Abuse_QtyLimit_Queue": 10.0,
  "US_ARI_Abuse_QtyLimit_Queue": 10.0,
  "AE_ARI_AccountLinkageInvestigation": 18.0,
  "AU_ARI_AccountLinkageInvestigation": 30.0,
  "BE_ARI_AccountLinkageInvestigation": 10.7,
  "BR_ARI_AccountLinkageInvestigation": 18.0,
  "CA_ARI_AccountLinkageInvestigation": 18.9,
  "DE_ARI_AccountLinkageInvestigation": 14.2,
  "EG_ARI_AccountLinkageInvestigation": 18.0,
  "ES_ARI_AccountLinkageInvestigation": 13.6,
  "FR_ARI_AccountLinkageInvestigation": 13.0,
  "GB_ARI_AccountLinkageInvestigation": 23.5,
  "IN_ARI_AccountLinkageInvestigation": 25.0,
  "IT_ARI_AccountLinkageInvestigation": 18.6,
  "JP_ARI_AccountLinkageInvestigation": 30.0,
  "MX_ARI_AccountLinkageInvestigation": 27.1,
  "NL_ARI_AccountLinkageInvestigation": 30.0,
  "PL_ARI_AccountLinkageInvestigation": 30.0,
  "SA_ARI_AccountLinkageInvestigation": 18.0,
  "SE_ARI_AccountLinkageInvestigation": 21.0,
  "SG_ARI_AccountLinkageInvestigation": 30.0,
  "TR_ARI_AccountLinkageInvestigation": 18.0,
  "US_ARI_AccountLinkageInvestigation": 17.1,
  "GB_ARI_AFNBEARSRefundApproval": 10.0,
  "US_ARI_AFNBEARSRefundApproval": 10.0,
  "DE_ARI_AFNFLRRefundApproval": 18.0,
  "ES_ARI_AFNFLRRefundApproval": 16.6,
  "FR_ARI_AFNFLRRefundApproval": 15.7,
  "GB_ARI_AFNFLRRefundApproval": 18.1,
  "IT_ARI_AFNFLRRefundApproval": 14.2,
  "US_ARI_AFNFLRRefundApproval": 18.5,
  "AE_ARI_AFNHolisticRefundApproval": 26.6,
  "AU_ARI_AFNHolisticRefundApproval": 18.4,
  "BE_ARI_AFNHolisticRefundApproval": 23.0,
  "CA_ARI_AFNHolisticRefundApproval": 14.8,
  "DE_ARI_AFNHolisticRefundApproval": 20.1,
  "EG_ARI_AFNHolisticRefundApproval": 30.0,
  "ES_ARI_AFNHolisticRefundApproval": 17.5,
  "FR_ARI_AFNHolisticRefundApproval": 18.5,
  "GB_ARI_AFNHolisticRefundApproval": 25.0,
  "IT_ARI_AFNHolisticRefundApproval": 19.7,
  "JP_ARI_AFNHolisticRefundApproval": 19.6,
  "MX_ARI_AFNHolisticRefundApproval": 18.8,
  "NL_ARI_AFNHolisticRefundApproval": 22.1,
  "PL_ARI_AFNHolisticRefundApproval": 29.2,
  "SA_ARI_AFNHolisticRefundApproval": 27.5,
  "SE_ARI_AFNHolisticRefundApproval": 21.0,
  "TR_ARI_AFNHolisticRefundApproval": 17.7,
  "US_ARI_AFNHolisticRefundApproval": 22.5,
  "AE_ARI_AFNRefundApproval": 16.0,
  "AU_ARI_AFNRefundApproval": 17.5,
  "BE_ARI_AFNRefundApproval": 13.2,
  "BR_ARI_AFNRefundApproval": 21.0,
  "CA_ARI_AFNRefundApproval": 24.0,
  "DE_ARI_AFNRefundApproval": 14.0,
  "EG_ARI_AFNRefundApproval": 17.2,
  "ES_ARI_AFNRefundApproval": 14.9,
  "FR_ARI_AFNRefundApproval": 13.6,
  "GB_ARI_AFNRefundApproval": 12.9,
  "IN_ARI_AFNRefundApproval": 14.0,
  "IT_ARI_AFNRefundApproval": 14.9,
  "JP_ARI_AFNRefundApproval": 19.0,
  "MX_ARI_AFNRefundApproval": 21.9,
  "NL_ARI_AFNRefundApproval": 15.3,
  "PL_ARI_AFNRefundApproval": 14.2,
  "SA_ARI_AFNRefundApproval": 15.0,
  "SE_ARI_AFNRefundApproval": 13.4,
  "SG_ARI_AFNRefundApproval": 16.9,
  "TR_ARI_AFNRefundApproval": 14.1,
  "US_ARI_AFNRefundApproval": 12.9,
  "GB_ARI_AFNRRRefundApproval": 10.3,
  "US_ARI_AFNRRRefundApproval": 17.3,
  "BR_ARI_BARSConcessionAbuse": 26.7,
  "CA_ARI_BARSConcessionAbuse": 23.6,
  "DE_ARI_BARSConcessionAbuse": 30.0,
  "ES_ARI_BARSConcessionAbuse": 30.0,
  "FR_ARI_BARSConcessionAbuse": 30.0,
  "GB_ARI_BARSConcessionAbuse": 24.9,
  "IT_ARI_BARSConcessionAbuse": 30.0,
  "MX_ARI_BARSConcessionAbuse": 25.0,
  "US_ARI_BARSConcessionAbuse": 20.2,
  "AE_ARI_BuyerClaimsAbuse": 24.1,
  "AU_ARI_BuyerClaimsAbuse": 26.5,
  "BE_ARI_BuyerClaimsAbuse": 29.7,
  "BR_ARI_BuyerClaimsAbuse": 25.0,
  "CA_ARI_BuyerClaimsAbuse": 20.8,
  "DE_ARI_BuyerClaimsAbuse": 26.1,
  "EG_ARI_BuyerClaimsAbuse": 24.5,
  "ES_ARI_BuyerClaimsAbuse": 27.3,
  "FR_ARI_BuyerClaimsAbuse": 26.9,
  "GB_ARI_BuyerClaimsAbuse": 21.7,
  "IT_ARI_BuyerClaimsAbuse": 25.7,
  "JP_ARI_BuyerClaimsAbuse": 25.2,
  "MX_ARI_BuyerClaimsAbuse": 23.2,
  "NL_ARI_BuyerClaimsAbuse": 25.8,
  "PL_ARI_BuyerClaimsAbuse": 29.9,
  "SA_ARI_BuyerClaimsAbuse": 22.8,
  "SE_ARI_BuyerClaimsAbuse": 20.1,
  "SG_ARI_BuyerClaimsAbuse": 21.8,
  "TR_ARI_BuyerClaimsAbuse": 26.5,
  "US_ARI_BuyerClaimsAbuse": 19.3,
  "US_ARI_CompEvidenceClaims": 7.0,
  "US_ARI_ConcessionAccountInvestigation": 17.7,
  "CA_ARI_ConcessionsAbuseCAPDNRReferrals": 14.6,
  "DE_ARI_ConcessionsAbuseCAPDNRReferrals": 17.7,
  "ES_ARI_ConcessionsAbuseCAPDNRReferrals": 18.9,
  "FR_ARI_ConcessionsAbuseCAPDNRReferrals": 18.6,
  "GB_ARI_ConcessionsAbuseCAPDNRReferrals": 18.2,
  "IN_ARI_ConcessionsAbuseCAPDNRReferrals": 25.0,
  "IT_ARI_ConcessionsAbuseCAPDNRReferrals": 18.4,
  "MX_ARI_ConcessionsAbuseCAPDNRReferrals": 19.6,
  "US_ARI_ConcessionsAbuseCAPDNRReferrals": 15.9,
  "IN_ARI_ConcessionsAbuseCAPMDRReferrals": 26.0,
  "US_ARI_ConcessionsAbuseCAPMDRReferrals": 20.3,
  "IN_ARI_ConcessionsAbuseCAPRRReferrals": 20.0,
  "DE_ARI_ConcessionsAbuseCSReferrals": 10.0,
  "ES_ARI_ConcessionsAbuseCSReferrals": 10.0,
  "FR_ARI_ConcessionsAbuseCSReferrals": 10.0,
  "GB_ARI_ConcessionsAbuseCSReferrals": 27.6,
  "IT_ARI_ConcessionsAbuseCSReferrals": 15.0,
  "JP_ARI_ConcessionsAbuseCSReferrals": 27.1,
  "MX_ARI_ConcessionsAbuseCSReferrals": 10.0,
  "US_ARI_ConcessionsAbuseCSReferrals": 18.6,
  "AE_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 30.0,
  "AU_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 30.0,
  "BE_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 10.0,
  "BR_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 25.4,
  "CA_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 20.4,
  "DE_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 26.1,
  "EG_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 30.0,
  "ES_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 27.5,
  "FR_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 30.0,
  "GB_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 22.0,
  "IT_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 30.0,
  "JP_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 28.0,
  "NL_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 10.0,
  "PL_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 20.0,
  "SA_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 30.0,
  "SE_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 26.6,
  "SG_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 28.7,
  "TR_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 27.1,
  "US_ARI_ConcessionsAbuseFailedReturnsRiskyOrders": 20.0,
  "AE_ARI_ConcessionsAbuseFLRReferrals": 18.1,
  "AU_ARI_ConcessionsAbuseFLRReferrals": 24.2,
  "BE_ARI_ConcessionsAbuseFLRReferrals": 20.1,
  "BR_ARI_ConcessionsAbuseFLRReferrals": 20.3,
  "CA_ARI_ConcessionsAbuseFLRReferrals": 14.6,
  "DE_ARI_ConcessionsAbuseFLRReferrals": 16.9,
  "EG_ARI_ConcessionsAbuseFLRReferrals": 22.0,
  "ES_ARI_ConcessionsAbuseFLRReferrals": 15.0,
  "FR_ARI_ConcessionsAbuseFLRReferrals": 18.4,
  "GB_ARI_ConcessionsAbuseFLRReferrals": 17.1,
  "IT_ARI_ConcessionsAbuseFLRReferrals": 12.4,
  "JP_ARI_ConcessionsAbuseFLRReferrals": 18.2,
  "MX_ARI_ConcessionsAbuseFLRReferrals": 19.9,
  "NL_ARI_ConcessionsAbuseFLRReferrals": 19.5,
  "PL_ARI_ConcessionsAbuseFLRReferrals": 19.1,
  "SA_ARI_ConcessionsAbuseFLRReferrals": 21.8,
  "SE_ARI_ConcessionsAbuseFLRReferrals": 19.4,
  "SG_ARI_ConcessionsAbuseFLRReferrals": 26.3,
  "TR_ARI_ConcessionsAbuseFLRReferrals": 23.5,
  "US_ARI_ConcessionsAbuseFLRReferrals": 15.9,
  "DE_ARI_ConcessionsAbuseFLRReferrals_Intransit": 10.0,
  "ES_ARI_ConcessionsAbuseFLRReferrals_Intransit": 14.8,
  "FR_ARI_ConcessionsAbuseFLRReferrals_Intransit": 20.4,
  "GB_ARI_ConcessionsAbuseFLRReferrals_Intransit": 7.8,
  "IT_ARI_ConcessionsAbuseFLRReferrals_Intransit": 10.0,
  "US_ARI_ConcessionsAbuseFLRReferrals_Intransit": 17.6,
  "CA_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 14.8,
  "DE_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 18.6,
  "ES_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 17.3,
  "FR_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 20.4,
  "GB_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 19.8,
  "IT_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 18.3,
  "MX_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 21.9,
  "US_ARI_ConcessionsAbuseHighPriCAPDNRReferrals": 16.0,
  "AE_ARI_ConcessionsAbusePFOCRiskyOrders": 20.0,
  "EG_ARI_ConcessionsAbusePFOCRiskyOrders": 20.0,
  "FR_ARI_ConcessionsAbusePFOCRiskyOrders": 20.0,
  "GB_ARI_ConcessionsAbusePFOCRiskyOrders": 20.0,
  "IT_ARI_ConcessionsAbusePFOCRiskyOrders": 20.0,
  "SA_ARI_ConcessionsAbusePFOCRiskyOrders": 20.0,
  "IN_ARI_ConcessionsAbusePreReturnsReferrals": 27.0,
  "AE_ARI_ConcessionsAbuseRiskyMFNOrders": 25.4,
  "AU_ARI_ConcessionsAbuseRiskyMFNOrders": 30.0,
  "BE_ARI_ConcessionsAbuseRiskyMFNOrders": 22.8,
  "BR_ARI_ConcessionsAbuseRiskyMFNOrders": 26.9,
  "DE_ARI_ConcessionsAbuseRiskyMFNOrders": 27.0,
  "EG_ARI_ConcessionsAbuseRiskyMFNOrders": 19.2,
  "ES_ARI_ConcessionsAbuseRiskyMFNOrders": 30.0,
  "FR_ARI_ConcessionsAbuseRiskyMFNOrders": 28.6,
  "GB_ARI_ConcessionsAbuseRiskyMFNOrders": 23.0,
  "IN_ARI_ConcessionsAbuseRiskyMFNOrders": 30.0,
  "IT_ARI_ConcessionsAbuseRiskyMFNOrders": 30.0,
  "NL_ARI_ConcessionsAbuseRiskyMFNOrders": 27.0,
  "PL_ARI_ConcessionsAbuseRiskyMFNOrders": 21.1,
  "SA_ARI_ConcessionsAbuseRiskyMFNOrders": 24.9,
  "SE_ARI_ConcessionsAbuseRiskyMFNOrders": 25.7,
  "SG_ARI_ConcessionsAbuseRiskyMFNOrders": 24.6,
  "TR_ARI_ConcessionsAbuseRiskyMFNOrders": 26.9,
  "US_ARI_ConcessionsAbuseRiskyMFNOrders": 20.9,
  "AE_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "AU_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "BE_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "BR_ARI_ConcessionsAbuseRiskyOrders": 27.7,
  "CA_ARI_ConcessionsAbuseRiskyOrders": 18.2,
  "DE_ARI_ConcessionsAbuseRiskyOrders": 24.0,
  "EG_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "ES_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "FR_ARI_ConcessionsAbuseRiskyOrders": 29.5,
  "GB_ARI_ConcessionsAbuseRiskyOrders": 22.5,
  "IN_ARI_ConcessionsAbuseRiskyOrders": 27.0,
  "IT_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "JP_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "MX_ARI_ConcessionsAbuseRiskyOrders": 25.0,
  "NL_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "PL_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "SA_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "SE_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "SG_ARI_ConcessionsAbuseRiskyOrders": 28.2,
  "TR_ARI_ConcessionsAbuseRiskyOrders": 30.0,
  "US_ARI_ConcessionsAbuseRiskyOrders": 16.6,
  "AE_ARI_ConcessionsAbuseRR": 24.3,
  "AU_ARI_ConcessionsAbuseRR": 30.0,
  "BE_ARI_ConcessionsAbuseRR": 10.0,
  "BR_ARI_ConcessionsAbuseRR": 29.9,
  "CA_ARI_ConcessionsAbuseRR": 26.0,
  "DE_ARI_ConcessionsAbuseRR": 20.0,
  "EG_ARI_ConcessionsAbuseRR": 30.0,
  "ES_ARI_ConcessionsAbuseRR": 22.2,
  "FR_ARI_ConcessionsAbuseRR": 17.6,
  "GB_ARI_ConcessionsAbuseRR": 30.0,
  "IT_ARI_ConcessionsAbuseRR": 24.1,
  "JP_ARI_ConcessionsAbuseRR": 19.5,
  "MX_ARI_ConcessionsAbuseRR": 29.9,
  "NL_ARI_ConcessionsAbuseRR": 24.3,
  "PL_ARI_ConcessionsAbuseRR": 24.6,
  "SA_ARI_ConcessionsAbuseRR": 30.0,
  "SE_ARI_ConcessionsAbuseRR": 19.9,
  "SG_ARI_ConcessionsAbuseRR": 10.0,
  "TR_ARI_ConcessionsAbuseRR": 22.0,
  "US_ARI_ConcessionsAbuseRR": 22.9,
  "BR_ARI_DNR_Concessions_Abuse": 25.8,
  "AE_ARI_DNRConcessionsAbuse": 19.0,
  "AU_ARI_DNRConcessionsAbuse": 30.0,
  "BE_ARI_DNRConcessionsAbuse": 20.4,
  "CA_ARI_DNRConcessionsAbuse": 17.5,
  "DE_ARI_DNRConcessionsAbuse": 23.5,
  "EG_ARI_DNRConcessionsAbuse": 22.3,
  "ES_ARI_DNRConcessionsAbuse": 30.0,
  "FR_ARI_DNRConcessionsAbuse": 10.0,
  "GB_ARI_DNRConcessionsAbuse": 21.5,
  "IN_ARI_DNRConcessionsAbuse": 26.0,
  "IT_ARI_DNRConcessionsAbuse": 10.0,
  "JP_ARI_DNRConcessionsAbuse": 30.0,
  "MX_ARI_DNRConcessionsAbuse": 23.0,
  "NL_ARI_DNRConcessionsAbuse": 23.0,
  "PL_ARI_DNRConcessionsAbuse": 21.0,
  "SA_ARI_DNRConcessionsAbuse": 19.6,
  "SE_ARI_DNRConcessionsAbuse": 24.8,
  "SG_ARI_DNRConcessionsAbuse": 28.8,
  "TR_ARI_DNRConcessionsAbuse": 26.0,
  "US_ARI_DNRConcessionsAbuse": 20.2,
  "AU_ARI_Drop_Ship_Abuse_Referrals": 30.0,
  "DE_ARI_Drop_Ship_Abuse_Referrals": 21.9,
  "ES_ARI_Drop_Ship_Abuse_Referrals": 10.0,
  "FR_ARI_Drop_Ship_Abuse_Referrals": 10.0,
  "GB_ARI_Drop_Ship_Abuse_Referrals": 24.1,
  "JP_ARI_Drop_Ship_Abuse_Referrals": 27.8,
  "US_ARI_Drop_Ship_Abuse_Referrals": 26.5,
  "GB_ARI_Email_account-appeals_uk": 16.3,
  "US_ARI_Email_account-appeals_us": 17.7,
  "IN_ARI_Email_account-reply_in": 22.0,
  "US_ARI_Email_nsr-appeal_us": 10.0,
  "IN_ARI_Email_nsr-appeals_in": 10.0,
  "JP_ARI_Email_qla-en_jp": 10.4,
  "JP_ARI_Email_qla-zh_jp": 16.2,
  "US_ARI_FF_ConcessionsAbuseRefundApproval": 6.8,
  "AE_ARI_In-transit": 23.0,
  "AU_ARI_In-transit": 26.4,
  "BE_ARI_In-transit": 20.3,
  "BR_ARI_In-transit": 23.3,
  "CA_ARI_In-transit": 17.2,
  "DE_ARI_In-transit": 12.9,
  "EG_ARI_In-transit": 20.8,
  "ES_ARI_In-transit": 11.7,
  "FR_ARI_In-transit": 11.3,
  "GB_ARI_In-transit": 17.0,
  "IN_ARI_In-transit": 17.0,
  "IT_ARI_In-transit": 12.4,
  "JP_ARI_In-transit": 26.1,
  "MX_ARI_In-transit": 16.7,
  "NL_ARI_In-transit": 14.2,
  "PL_ARI_In-transit": 12.9,
  "SA_ARI_In-transit": 21.4,
  "SE_ARI_In-transit": 18.2,
  "SG_ARI_In-transit": 30.0,
  "TR_ARI_In-transit": 13.1,
  "US_ARI_In-transit": 15.0,
  "US_ARI_LinkageRefundApproval": 21.7,
  "DE_ARI_MDR_Account_Investigation_BAU": 24.0,
  "ES_ARI_MDR_Account_Investigation_BAU": 26.0,
  "FR_ARI_MDR_Account_Investigation_BAU": 21.2,
  "GB_ARI_MDR_Account_Investigation_BAU": 23.2,
  "IT_ARI_MDR_Account_Investigation_BAU": 25.2,
  "AE_ARI_MFNEgregious": 30.0,
  "AU_ARI_MFNEgregious": 30.0,
  "BE_ARI_MFNEgregious": 10.0,
  "BR_ARI_MFNEgregious": 30.0,
  "CA_ARI_MFNEgregious": 30.0,
  "DE_ARI_MFNEgregious": 29.5,
  "EG_ARI_MFNEgregious": 30.0,
  "ES_ARI_MFNEgregious": 30.0,
  "FR_ARI_MFNEgregious": 29.0,
  "GB_ARI_MFNEgregious": 30.0,
  "IT_ARI_MFNEgregious": 29.6,
  "JP_ARI_MFNEgregious": 30.0,
  "MX_ARI_MFNEgregious": 30.0,
  "NL_ARI_MFNEgregious": 30.0,
  "PL_ARI_MFNEgregious": 30.0,
  "SA_ARI_MFNEgregious": 30.0,
  "SE_ARI_MFNEgregious": 30.0,
  "SG_ARI_MFNEgregious": 10.0,
  "TR_ARI_MFNEgregious": 30.0,
  "US_ARI_MFNEgregious": 30.0,
  "EG_ARI_NSRAccountInvestigation": 17.9,
  "PL_ARI_NSRAccountInvestigation": 10.0,
  "AE_ARI_NSRConcessionsAbuse": 29.7,
  "AU_ARI_NSRConcessionsAbuse": 30.0,
  "BE_ARI_NSRConcessionsAbuse": 10.0,
  "BR_ARI_NSRConcessionsAbuse": 29.3,
  "CA_ARI_NSRConcessionsAbuse": 30.0,
  "DE_ARI_NSRConcessionsAbuse": 19.5,
  "EG_ARI_NSRConcessionsAbuse": 30.0,
  "ES_ARI_NSRConcessionsAbuse": 21.0,
  "FR_ARI_NSRConcessionsAbuse": 28.3,
  "GB_ARI_NSRConcessionsAbuse": 21.8,
  "IT_ARI_NSRConcessionsAbuse": 24.9,
  "JP_ARI_NSRConcessionsAbuse": 28.6,
  "MX_ARI_NSRConcessionsAbuse": 30.0,
  "NL_ARI_NSRConcessionsAbuse": 10.0,
  "PL_ARI_NSRConcessionsAbuse": 30.0,
  "SA_ARI_NSRConcessionsAbuse": 26.0,
  "SE_ARI_NSRConcessionsAbuse": 28.1,
  "SG_ARI_NSRConcessionsAbuse": 30.0,
  "TR_ARI_NSRConcessionsAbuse": 10.0,
  "US_ARI_NSRConcessionsAbuse": 24.1,
  "AE_ARI_NSRSOU": 10.0,
  "AU_ARI_NSRSOU": 23.0,
  "CA_ARI_NSRSOU": 29.3,
  "DE_ARI_NSRSOU": 23.2,
  "ES_ARI_NSRSOU": 25.1,
  "FR_ARI_NSRSOU": 24.1,
  "GB_ARI_NSRSOU": 27.4,
  "IT_ARI_NSRSOU": 27.0,
  "JP_ARI_NSRSOU": 17.0,
  "MX_ARI_NSRSOU": 21.3,
  "NL_ARI_NSRSOU": 17.5,
  "PL_ARI_NSRSOU": 10.0,
  "SE_ARI_NSRSOU": 10.0,
  "US_ARI_NSRSOU": 27.7,
  "IN_ARI_RMConcessionsAbuse": 10.0,
  "AE_ARI_SellerInitiatedRefund": 15.5,
  "AU_ARI_SellerInitiatedRefund": 25.3,
  "BE_ARI_SellerInitiatedRefund": 20.4,
  "BR_ARI_SellerInitiatedRefund": 24.7,
  "CA_ARI_SellerInitiatedRefund": 12.5,
  "DE_ARI_SellerInitiatedRefund": 20.0,
  "EG_ARI_SellerInitiatedRefund": 21.4,
  "ES_ARI_SellerInitiatedRefund": 18.1,
  "FR_ARI_SellerInitiatedRefund": 16.3,
  "GB_ARI_SellerInitiatedRefund": 12.7,
  "IT_ARI_SellerInitiatedRefund": 18.9,
  "JP_ARI_SellerInitiatedRefund": 19.5,
  "MX_ARI_SellerInitiatedRefund": 19.9,
  "NL_ARI_SellerInitiatedRefund": 19.6,
  "PL_ARI_SellerInitiatedRefund": 25.4,
  "SA_ARI_SellerInitiatedRefund": 20.0,
  "SE_ARI_SellerInitiatedRefund": 18.5,
  "SG_ARI_SellerInitiatedRefund": 10.0,
  "TR_ARI_SellerInitiatedRefund": 22.9,
  "US_ARI_SellerInitiatedRefund": 14.0,
  "AE_ARI_Email_ofm": 13.1,
  "AU_ARI_Email_ofm": 14.9,
  "BE_ARI_Email_ofm": 10.0,
  "BR_ARI_Email_ofm": 14.2,
  "CA_ARI_Email_ofm": 15.2,
  "DE_ARI_Email_ofm": 16.0,
  "EG_ARI_Email_ofm": 12.4,
  "ES_ARI_Email_ofm": 14.4,
  "FR_ARI_Email_ofm": 13.1,
  "GB_ARI_Email_ofm": 16.0,
  "IN_ARI_Email_ofm": 16.0,
  "IT_ARI_Email_ofm": 15.0,
  "MX_ARI_Email_ofm": 12.9,
  "NL_ARI_Email_ofm": 14.3,
  "PL_ARI_Email_ofm": 13.9,
  "SA_ARI_Email_ofm": 13.3,
  "SE_ARI_Email_ofm": 12.4,
  "SG_ARI_Email_ofm": 11.3,
  "TR_ARI_Email_ofm": 12.0,
  "US_ARI_Email_ofm": 14.0,
  "AE_ARI_Email_contra": 10.0,
  "AU_ARI_Email_contra": 10.1,
  "BR_ARI_Email_contra": 11.7,
  "CA_ARI_Email_contra": 10.0,
  "DE_ARI_Email_contra": 12.1,
  "EG_ARI_Email_contra": 13.2,
  "ES_ARI_Email_contra": 11.5,
  "FR_ARI_Email_contra": 13.3,
  "GB_ARI_Email_contra": 15.2,
  "IN_ARI_Email_contra": 15.0,
  "IT_ARI_Email_contra": 12.4,
  "JP_ARI_Email_contra": 10.0,
  "MX_ARI_Email_contra": 10.0,
  "NL_ARI_Email_contra": 10.0,
  "PL_ARI_Email_contra": 22.0,
  "SA_ARI_Email_contra": 10.0,
  "SG_ARI_Email_contra": 10.0,
  "TR_ARI_Email_contra": 16.4,
  "US_ARI_Email_contra": 11.9,
  "AE_ARI_Email_suspect-abuse": 17.3,
  "AU_ARI_Email_suspect-abuse": 17.9,
  "BE_ARI_Email_suspect-abuse": 14.4,
  "BR_ARI_Email_suspect-abuse": 16.7,
  "EG_ARI_Email_suspect-abuse": 17.3,
  "NL_ARI_Email_suspect-abuse": 16.5,
  "PL_ARI_Email_suspect-abuse": 14.8,
  "SA_ARI_Email_suspect-abuse": 18.3,
  "SE_ARI_Email_suspect-abuse": 16.9,
  "SG_ARI_Email_suspect-abuse": 10.0,
  "TR_ARI_Email_suspect-abuse": 13.9,
  "AE_ARI_Email_qla": 24.0,
  "AU_ARI_Email_qla": 10.0,
  "BR_ARI_Email_qla": 13.7,
  "CA_ARI_Email_qla": 13.4,
  "DE_ARI_Email_qla": 15.8,
  "EG_ARI_Email_qla": 20.9,
  "ES_ARI_Email_qla": 5.0,
  "FR_ARI_Email_qla": 10.0,
  "GB_ARI_Email_qla": 15.3,
  "IN_ARI_Email_qla": 14.9,
  "IT_ARI_Email_qla": 12.5,
  "JP_ARI_Email_qla": 14.7,
  "MX_ARI_Email_qla": 10.0,
  "NL_ARI_Email_qla": 12.7,
  "PL_ARI_Email_qla": 13.4,
  "SA_ARI_Email_qla": 21.4,
  "SE_ARI_Email_qla": 22.0,
  "SG_ARI_Email_qla": 22.0,
  "TR_ARI_Email_qla": 12.5,
  "US_ARI_Email_qla": 11.6,
  "AE_ARI_Email_neat": 11.8,
  "AU_ARI_Email_neat": 12.7,
  "BR_ARI_Email_neat": 10.0,
  "CA_ARI_Email_neat": 22.0,
  "DE_ARI_Email_neat": 16.6,
  "ES_ARI_Email_neat": 15.9,
  "FR_ARI_Email_neat": 14.0,
  "GB_ARI_Email_neat": 13.1,
  "IN_ARI_Email_neat": 19.0,
  "IT_ARI_Email_neat": 16.2,
  "JP_ARI_Email_neat": 13.0,
  "MX_ARI_Email_neat": 22.0,
  "NL_ARI_Email_neat": 12.1,
  "SG_ARI_Email_neat": 10.0,
  "TR_ARI_Email_neat": 12.7,
  "US_ARI_Email_neat": 19.0,
  "AE_ARI_Email_maa-emails": 10.0,
  "AU_ARI_Email_maa-emails": 10.0,
  "BR_ARI_Email_maa-emails": 10.0,
  "CA_ARI_Email_maa-emails": 10.0,
  "DE_ARI_Email_maa-emails": 10.0,
  "EG_ARI_Email_maa-emails": 10.0,
  "ES_ARI_Email_maa-emails": 10.0,
  "FR_ARI_Email_maa-emails": 10.0,
  "GB_ARI_Email_maa-emails": 10.0,
  "IT_ARI_Email_maa-emails": 10.0,
  "JP_ARI_Email_maa-emails": 11.4,
  "MX_ARI_Email_maa-emails": 10.0,
  "NL_ARI_Email_maa-emails": 10.0,
  "PL_ARI_Email_maa-emails": 10.0,
  "SA_ARI_Email_maa-emails": 10.0,
  "SE_ARI_Email_maa-emails": 8.5,
  "SG_ARI_Email_maa-emails": 12.9,
  "TR_ARI_Email_maa-emails": 10.0,
  "US_ARI_Email_maa-emails": 10.0,
  "DE_ARI_Email_buyer-returns": 11.7,
  "ES_ARI_Email_buyer-returns": 10.5,
  "FR_ARI_Email_buyer-returns": 11.7,
  "GB_ARI_Email_buyer-returns": 11.3,
  "IN_ARI_Email_buyer-returns": 12.8,
  "IT_ARI_Email_buyer-returns": 11.0,
  "US_ARI_Email_buyer-returns": 11.0,
  "AE_ARI_Email_buyer-claims": 15.6,
  "AU_ARI_Email_buyer-claims": 22.0,
  "NL_ARI_Email_buyer-claims": 20.5,
  "SA_ARI_Email_buyer-claims": 15.0,
  "SG_ARI_Email_buyer-claims": 22.0,
  "TR_ARI_Email_buyer-claims": 10.0,
  "DE_ARI_Email_buyer-claims-abuse": 15.9,
  "ES_ARI_Email_buyer-claims-abuse": 10.6,
  "FR_ARI_Email_buyer-claims-abuse": 10.0,
  "GB_ARI_Email_buyer-claims-abuse": 13.0,
}






// content.js

// Create a div element
const customBox = document.createElement('div');

// Set the styles for the box
customBox.style.width = '300px';
customBox.style.height = '70px';
customBox.style.backgroundColor = '#ffffff';
customBox.style.borderRadius = '10px';
customBox.style.position = 'fixed';

// Set the position using x and y coordinates
const xCoordinate = 300; // replace with your desired x-coordinate
const yCoordinate = 0; // replace with your desired y-coordinate
customBox.style.left = `${xCoordinate}px`;
customBox.style.top = `${yCoordinate}px`;

customBox.style.zIndex = '9999';

// Add some data to the box
customBox.innerHTML = `
<div id="qname">Queue : </div>
<div id="qiph">QIPH : </div>
<div id="timerDisplay"> Timer : </div>
<div>CPH : </div>

`;

// Append the box to the document body
document.body.appendChild(customBox);





function taskdataview() {

  const a = document.getElementsByClassName("pi-widgets nautilus-widgets")[0];
  const jsonstring = a.dataset.pageContext;

  try {
    const jsonObject = JSON.parse(jsonstring);
    let que = jsonObject.queueName;
    document.getElementById("qname").innerText= `Queue : ${jsonObject.queueName}`;
    document.getElementById("qiph").innerText=`QIPH : ${IPHdata[que]}`

    
    
  } catch (error) {
    console.error("Error parsing JSON:", error);
  }
 

}




// JavaScript Timer Function
function startTimer() {
  let seconds = 0;
  const timerDisplay = document.getElementById('timerDisplay');

  function updateTimerDisplay() {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    timerDisplay.innerText = ` Timer :${minutes}m ${remainingSeconds}s`;
  }

  // Start the timer
  const timerInterval = setInterval(function () {
    seconds++;
    updateTimerDisplay();
  }, 1000);

  // You can stop the timer by calling clearInterval(timerInterval)
  // For example, to stop after 5 seconds:
  // setTimeout(function() { clearInterval(timerInterval); }, 5000);
}

// Call the timer function when the page loads
window.onload = function () {
  startTimer();
  taskdataview();
};
